name: "Service Mesh Performance Testing with Meshery"
description: "Validate SMP specification using Meshery"
author: "Layer5"

inputs:
  provider_token:
    description: "Provider token to use. NOTE: value of the 'token' key in auth.json"
  platform:
    description: "Platform to deploy meshery on. Possible values: docker, kubernetes"
    default: docker
  profile_filename:
    description: "Name of the file containing SMP profile"
    required: true

runs:
  using: "node12"
  main: "main.js"

branding:
  icon: 'check-circle'
  color: 'green'
